created virtual environment CPython3.8.2.final.0-64 in 653ms
  creator CPython3Posix(dest=/local/naicheng.52792664.0/env, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/naicheng/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/torch-1.9.0+computecanada-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: typing-extensions in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from torch) (3.10.0.0+computecanada)
Installing collected packages: torch
Successfully installed torch-1.9.0+computecanada
/project/6001286/naicheng/Naicheng/res/fnn
[[0.  ]
 [0.75]
 [0.5 ]
 [0.5 ]
 [0.25]
 [0.  ]
 [0.  ]
 [0.5 ]
 [0.25]
 [0.5 ]
 [0.25]
 [0.5 ]
 [0.5 ]
 [0.75]
 [0.  ]]
Traceback (most recent call last):
  File "random_traning.py", line 51, in <module>
    disc_loss, gen_loss = training_bce(gen, disc, z_dim, epoch_step, my_dataloader,
  File "/project/6001286/naicheng/Naicheng/res/fnn/training.py", line 30, in training_bce
    for real , _ in dataloader:    
  File "/local/naicheng.52792664.0/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/local/naicheng.52792664.0/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/local/naicheng.52792664.0/env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/local/naicheng.52792664.0/env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/6001286/naicheng/Naicheng/res/process_data/dataset.py", line 46, in __getitem__
    tensor = torch.reshape(tensor, [1, self.row_dim, self.column_dim])
RuntimeError: shape '[1, 31, 1]' is invalid for input of size 15
